"""add resumes_url to import_batch

Revision ID: c6f0a8329075
Revises: b322f671e4b3
Create Date: 2026-06-29 10:34:29.356532

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6f0a8329075"
down_revision: str | Sequence[str] | None = "b322f671e4b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "import_batches",
        sa.Column("resumes_url", sa.String(length=1024), nullable=True),
    )
    op.add_column(
        "import_validation_issues",
        sa.Column("issue_code", sa.String(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("import_validation_issues", "issue_code")
    op.drop_column("import_batches", "resumes_url")
    # ### end Alembic commands ###
