"""add import_batch_id to project

Revision ID: ddfc94f635f5
Revises: c6f0a8329075
Create Date: 2026-06-29 10:39:43.681488

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ddfc94f635f5"
down_revision: str | Sequence[str] | None = "c6f0a8329075"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("import_batch_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None,
        "projects",
        "import_batches",
        ["import_batch_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "projects", type_="foreignkey")
    op.drop_column("projects", "import_batch_id")
    # ### end Alembic commands ###
