"""Curated technical skills vocabulary for resume keyword extraction.

Modeled on the skill dictionaries used by open-source resume parsers
(pyresparser's skills.csv approach), but curated for this platform's
data-science / software-engineering student cohorts.
"""

from __future__ import annotations

SKILLS_VOCABULARY: list[str] = [
    # ── Programming languages ────────────────────────────────────────────
    "Python",
    "Java",
    "C++",
    "C#",
    "C",
    "R",
    "Go",
    "Rust",
    "Kotlin",
    "Swift",
    "Scala",
    "TypeScript",
    "JavaScript",
    "PHP",
    "Ruby",
    "Perl",
    "Julia",
    "MATLAB",
    "Fortran",
    "Haskell",
    "Dart",
    "Objective-C",
    "SQL",
    "Bash",
    "PowerShell",
    "Assembly",
    "VHDL",
    "Verilog",
    "Solidity",
    # ── Machine learning / AI ────────────────────────────────────────────
    "Machine Learning",
    "Deep Learning",
    "Artificial Intelligence",
    "PyTorch",
    "TensorFlow",
    "Keras",
    "Scikit-learn",
    "XGBoost",
    "LightGBM",
    "CatBoost",
    "Natural Language Processing",
    "NLP",
    "Computer Vision",
    "OpenCV",
    "NLTK",
    "spaCy",
    "Transformers",
    "Hugging Face",
    "LLM",
    "Large Language Models",
    "Generative AI",
    "GAN",
    "CNN",
    "RNN",
    "LSTM",
    "Reinforcement Learning",
    "Neural Networks",
    "BERT",
    "GPT",
    "LangChain",
    "LlamaIndex",
    "RAG",
    "Prompt Engineering",
    "Fine-tuning",
    "MLOps",
    "MLflow",
    "Weights & Biases",
    "Object Detection",
    "Image Segmentation",
    "Speech Recognition",
    "Recommendation Systems",
    "Time Series",
    "Anomaly Detection",
    "Feature Engineering",
    "Model Deployment",
    "Sentiment Analysis",
    "Text Classification",
    "Named Entity Recognition",
    "YOLO",
    "Stable Diffusion",
    "OpenAI API",
    "Vector Databases",
    "Embeddings",
    "Semantic Search",
    "AutoML",
    "ONNX",
    # ── Data science / analytics ─────────────────────────────────────────
    "NumPy",
    "Pandas",
    "Matplotlib",
    "Seaborn",
    "Plotly",
    "SciPy",
    "Statsmodels",
    "Data Analysis",
    "Data Science",
    "Data Visualization",
    "Data Mining",
    "Data Engineering",
    "Statistics",
    "Probability",
    "Linear Algebra",
    "Regression",
    "Classification",
    "Clustering",
    "Hypothesis Testing",
    "A/B Testing",
    "ETL",
    "Data Cleaning",
    "Exploratory Data Analysis",
    "EDA",
    "Big Data",
    "Data Warehousing",
    "Tableau",
    "Power BI",
    "Looker",
    "Excel",
    "Google Sheets",
    "Dash",
    "Streamlit",
    "Gradio",
    "Shiny",
    "D3.js",
    # ── Databases ────────────────────────────────────────────────────────
    "MySQL",
    "PostgreSQL",
    "SQLite",
    "MongoDB",
    "Redis",
    "Cassandra",
    "DynamoDB",
    "Oracle",
    "SQL Server",
    "MariaDB",
    "Neo4j",
    "Firebase",
    "Firestore",
    "Supabase",
    "Elasticsearch",
    "Snowflake",
    "BigQuery",
    "Redshift",
    "ClickHouse",
    "Pinecone",
    "ChromaDB",
    "FAISS",
    "Qdrant",
    # ── Big data / pipelines ─────────────────────────────────────────────
    "Apache Spark",
    "Spark",
    "Hadoop",
    "Kafka",
    "Airflow",
    "dbt",
    "Flink",
    "Hive",
    "Pig",
    "MapReduce",
    "Databricks",
    "PySpark",
    "Beam",
    "NiFi",
    # ── Web / frontend ───────────────────────────────────────────────────
    "React",
    "Vue",
    "Angular",
    "Svelte",
    "Next.js",
    "Nuxt",
    "HTML",
    "CSS",
    "Sass",
    "Tailwind CSS",
    "Bootstrap",
    "Material UI",
    "jQuery",
    "Redux",
    "Webpack",
    "Vite",
    "Web Development",
    "Responsive Design",
    "Figma",
    "UI/UX",
    "Frontend Development",
    # ── Backend / frameworks ─────────────────────────────────────────────
    "Node.js",
    "Express",
    "Django",
    "Flask",
    "FastAPI",
    "Spring Boot",
    "Spring",
    "Laravel",
    "Rails",
    "ASP.NET",
    ".NET",
    "GraphQL",
    "REST API",
    "RESTful API",
    "gRPC",
    "Microservices",
    "WebSockets",
    "OAuth",
    "JWT",
    "Backend Development",
    "Full Stack Development",
    "API Development",
    "Socket.io",
    "Celery",
    "RabbitMQ",
    # ── Mobile ───────────────────────────────────────────────────────────
    "Android",
    "iOS",
    "React Native",
    "Flutter",
    "SwiftUI",
    "Jetpack Compose",
    "Mobile Development",
    "Xamarin",
    # ── DevOps / cloud ───────────────────────────────────────────────────
    "Docker",
    "Kubernetes",
    "AWS",
    "Amazon Web Services",
    "GCP",
    "Google Cloud",
    "Azure",
    "Terraform",
    "Ansible",
    "Jenkins",
    "CI/CD",
    "GitHub Actions",
    "GitLab CI",
    "CircleCI",
    "Linux",
    "Unix",
    "Nginx",
    "Apache",
    "Heroku",
    "Vercel",
    "Netlify",
    "Railway",
    "Lambda",
    "EC2",
    "S3",
    "CloudFormation",
    "Prometheus",
    "Grafana",
    "DevOps",
    "SRE",
    "Serverless",
    "Cloud Computing",
    # ── Tools / practices ────────────────────────────────────────────────
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "Jira",
    "Confluence",
    "Agile",
    "Scrum",
    "Kanban",
    "TDD",
    "Unit Testing",
    "Pytest",
    "Jest",
    "Selenium",
    "Cypress",
    "Playwright",
    "Postman",
    "Swagger",
    "VS Code",
    "Jupyter",
    "Anaconda",
    "Vim",
    "IntelliJ",
    "Eclipse",
    "LaTeX",
    "Markdown",
    "Version Control",
    "Code Review",
    "Debugging",
    "Design Patterns",
    "Object Oriented Programming",
    "OOP",
    "Functional Programming",
    "Data Structures",
    "Algorithms",
    "System Design",
    "Distributed Systems",
    "Operating Systems",
    "Computer Networks",
    "Cybersecurity",
    "Cryptography",
    "Penetration Testing",
    "Blockchain",
    "Web3",
    "Smart Contracts",
    "IoT",
    "Embedded Systems",
    "Arduino",
    "Raspberry Pi",
    "Robotics",
    "ROS",
    "Game Development",
    "Unity",
    "Unreal Engine",
    # ── Competitive / platforms ──────────────────────────────────────────
    "Kaggle",
    "LeetCode",
    "Codeforces",
    "HackerRank",
    "CodeChef",
    "Competitive Programming",
]

# Pre-computed lowercase set for O(1) membership checks.
SKILLS_VOCABULARY_LOWER: frozenset[str] = frozenset(
    s.lower() for s in SKILLS_VOCABULARY
)
